### ISSUE TITLE
How does the step size work?

### ISSUE THREAD

**Issue by tawhidkhn63** [realChesta/slide-extractor#1]
Does your program look at the frame in the video every second, every 2 second, etc? I'm new to open CV and confused how the step sizing works. Thank you.

**Comment by realChesta** [comment]
Hi, the step size refers to the amount of frames that are skipped in each iteration. With a step size of 1, the program would look at each frame of the video (with an FPS of 30, that would be 30 frames in every second). I recommend setting it higher though, as there usually isn't a new slide in each frame, but maybe only one every few minutes.
